# Generated by Django 6.0.1 on 2026-02-06 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessoryName', models.CharField(max_length=100)),
                ('accessoryType', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'accessory',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('fuelType', models.CharField(max_length=30)),
                ('transmission', models.CharField(max_length=30)),
                ('mileage', models.FloatField()),
                ('launchYear', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('userEmail', models.EmailField(max_length=254, unique=True)),
                ('userPassword', models.CharField(max_length=255)),
                ('userPhone', models.CharField(max_length=15, null=True)),
                ('userCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('userStatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='CarAccessoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.accessory')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.car')),
            ],
            options={
                'db_table': 'car_accessory_mapping',
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('searchedAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.user')),
            ],
            options={
                'db_table': 'search_history',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.user')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparedAt', models.DateTimeField(auto_now_add=True)),
                ('car1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car1', to='test1.car')),
                ('car2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car2', to='test1.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.user')),
            ],
            options={
                'db_table': 'comparison',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminRole', models.CharField(max_length=50)),
                ('adminAccessLevel', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test1.user')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interactionType', models.CharField(max_length=30)),
                ('durationSeconds', models.IntegerField(null=True)),
                ('interactionDate', models.DateTimeField()),
                ('deviceType', models.CharField(max_length=20, null=True)),
                ('referrer', models.CharField(max_length=255, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.user')),
            ],
            options={
                'db_table': 'user_interaction',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferredFuel', models.CharField(max_length=30)),
                ('maxBudget', models.IntegerField()),
                ('preferredBrand', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test1.user')),
            ],
            options={
                'db_table': 'user_preference',
            },
        ),
    ]
