# Generated by Django 6.0.1 on 2026-02-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productStatus',
        ),
    ]
