# Generated by Django 6.0.1 on 2026-02-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_product_productstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productStatus',
            field=models.BooleanField(default=True),
        ),
    ]
