# Generated by Django 6.0.1 on 2026-02-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
