# Generated by Django 6.0.1 on 2026-02-06 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('companyEmail', models.EmailField(max_length=254)),
                ('companyLocation', models.CharField(max_length=100)),
                ('companyActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyGST', models.CharField(max_length=50)),
                ('companyFounded', models.DateField()),
                ('companyWebsite', models.URLField()),
                ('companyPhone', models.CharField(max_length=15)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.company')),
            ],
            options={
                'db_table': 'company_profile',
            },
        ),
    ]
